# Generated by Django 5.0.3 on 2026-01-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('store_keeper', 'Store Keeper'), ('inventory_manager', 'Inventory Manager'), ('requester', 'Requester'), ('vendor', 'Vendor')], max_length=20),
        ),
    ]
