# Generated by Django 5.0.3 on 2026-01-09 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_blocked_alter_userprofile_role_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, help_text='Whether 2FA is enabled for this user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_otp_used',
            field=models.CharField(blank=True, help_text='Last used OTP to prevent replay attacks', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_backup_codes',
            field=models.JSONField(blank=True, default=list, help_text='Backup codes for 2FA recovery'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='TOTP secret for Google Authenticator', max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('request_type', models.CharField(choices=[('password_reset', 'Password Reset'), ('login_verification', 'Login Verification')], default='password_reset', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
