# Generated by Django 5.0.3 on 2026-01-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_is_2fa_enabled_userprofile_last_otp_used_and_more'),
    ]

    operations = [
    ]
