# Generated by Django 5.0.3 on 2026-01-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorName', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('fullAddress', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('GSTN', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('vendorType', models.CharField(choices=[('purchase', 'Purchase'), ('service', 'Service'), ('scrap', 'Scrap')], default='purchase', max_length=10)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('plantId', models.IntegerField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
