# Generated by Django 5.0.3 on 2026-01-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendor_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='delivery_time_rating',
            field=models.CharField(choices=[('5.0 - Excellent', '5.0 - Excellent'), ('4.5 - Very Good', '4.5 - Very Good'), ('4.0 - Good', '4.0 - Good'), ('3.5 - Average', '3.5 - Average'), ('3.0 - Below Average', '3.0 - Below Average'), ('2.0 - Poor', '2.0 - Poor'), ('Not Rated', 'Not Rated')], default='Not Rated', help_text='Delivery time rating', max_length=25),
        ),
        migrations.AddField(
            model_name='vendor',
            name='overall_avg_rating',
            field=models.CharField(choices=[('5.0 - Excellent', '5.0 - Excellent'), ('4.5 - Very Good', '4.5 - Very Good'), ('4.0 - Good', '4.0 - Good'), ('3.5 - Average', '3.5 - Average'), ('3.0 - Below Average', '3.0 - Below Average'), ('2.0 - Poor', '2.0 - Poor'), ('Not Rated', 'Not Rated')], default='Not Rated', help_text='Overall average rating', max_length=25),
        ),
        migrations.AddField(
            model_name='vendor',
            name='quality_price_rating',
            field=models.CharField(choices=[('5.0 - Excellent', '5.0 - Excellent'), ('4.5 - Very Good', '4.5 - Very Good'), ('4.0 - Good', '4.0 - Good'), ('3.5 - Average', '3.5 - Average'), ('3.0 - Below Average', '3.0 - Below Average'), ('2.0 - Poor', '2.0 - Poor'), ('Not Rated', 'Not Rated')], default='Not Rated', help_text='Quality and price rating', max_length=25),
        ),
    ]
