# Generated by Django 5.0.3 on 2026-01-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_delivery_time_rating_and_more'),
    ]

    operations = [
    ]
